apiVersion: v1
kind: Service
metadata:
  name: application-idv-service-expose
spec:
  type: NodePort
  selector:
    app: application-idv-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8