version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: my-rabbit
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  bnb_client_portal:
    container_name: bnb_client_portal
    build:
      context: ../angular
      dockerfile: Angular.Dockerfile
    ports:
      - "8080:80"
  bnb_boat_api:
    container_name: bnb_boat_api
    build:
      context: .
      dockerfile: Boat.Dockerfile
    environment:
      "ASPNETCORE_ENVIRONMENT": "Production"
      "ConnectionStrings:Default": ""
      "App:SelfUrl": ""
      "App:ClientUrl": ""
      "App:RedirectAllowedUrls": ""
      "App:CorsOrigins": ""
      "AuthServer:Authority": ""
      "AuthServer:RequireHttpsMetadata": ""
      "AuthServer:SwaggerClientId": ""
      "AuthServer:SwaggerClientSecret": ""
      "RabbitMq:Host": ""
      "RabbitMq:UserName": ""
      "RabbitMq:Password": ""
      "RabbitMq:VirtualHost": ""
      "StringEncryption:DefaultPassPhrase": ""
      "Stripe:ApiKey": ""
    ports:
      - "21021:80"
    volumes:
      - ./tmp-build/BNB/BNBBoat-Webhost/logs:/app/Logs
      - ./tmp-build/BNB/BNBBoat-Webhost/.aspnet/https:/root/.aspnet/https:ro
      - ./tmp-build/BNB/BNBBoat-Webhost/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    links:
      - rabbitmq:rabbitmq
    depends_on:
      - rabbitmq

  bnb_booking_api:
    container_name: bnb_booking_api
    build:
      context: .
      dockerfile: Booking.Dockerfile
    environment:
      "ASPNETCORE_ENVIRONMENT": "Production"
      "ConnectionStrings:Default": ""
      "App:SelfUrl": ""
      "App:ClientUrl": ""
      "App:RedirectAllowedUrls": ""
      "App:CorsOrigins": ""
      "AuthServer:Authority": ""
      "AuthServer:RequireHttpsMetadata": ""
      "AuthServer:SwaggerClientId": ""
      "AuthServer:SwaggerClientSecret": ""
      "RabbitMq:Host": ""
      "RabbitMq:UserName": ""
      "RabbitMq:Password": ""
      "RabbitMq:VirtualHost": ""
      "StringEncryption:DefaultPassPhrase": ""
      "Stripe:ApiKey": ""
    ports:
      - "21022:80"
    volumes:
      - ./tmp-build/BNB/BNBBooking-Host/logs:/app/Logs
      - ./tmp-build/BNB/BNBBooking-Host/.aspnet/https:/root/.aspnet/https:ro
      - ./tmp-build/BNB/BNBBooking-Host/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    links:
      - rabbitmq:rabbitmq
    depends_on:
      - rabbitmq
  bnb_payment_api:
    container_name: bnb_payment_api
    build:
      context: .
      dockerfile: Payment.Dockerfile
    environment:
      "ASPNETCORE_ENVIRONMENT": "Production"
      "ConnectionStrings:Default": ""
      "App:SelfUrl": ""
      "App:ClientUrl": ""
      "App:RedirectAllowedUrls": ""
      "App:CorsOrigins": ""
      "AuthServer:Authority": ""
      "AuthServer:RequireHttpsMetadata": ""
      "AuthServer:SwaggerClientId": ""
      "AuthServer:SwaggerClientSecret": ""
      "RabbitMq:Host": ""
      "RabbitMq:UserName": ""
      "RabbitMq:Password": ""
      "RabbitMq:VirtualHost": ""
      "StringEncryption:DefaultPassPhrase": ""
      "Stripe:ApiKey": ""
    ports:
      - "21023:80"
    volumes:
      - ./tmp-build/BNB/BNBPayment-Host/logs:/app/Logs
      - ./tmp-build/BNB/BNBPayment-Host/.aspnet/https:/root/.aspnet/https:ro
      - ./tmp-build/BNB/BNBPayment-Host/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    links:
      - rabbitmq:rabbitmq
    depends_on:
      - rabbitmq
  bnb_core_api:
    container_name: bnb_core_api
    build:
      context: .
      dockerfile: Core.Dockerfile
    environment:
      "ASPNETCORE_ENVIRONMENT": "Production"
      "ConnectionStrings:Default": ""
      "App:SelfUrl": ""
      "App:ClientUrl": ""
      "App:RedirectAllowedUrls": ""
      "App:CorsOrigins": ""
      "AuthServer:Authority": ""
      "AuthServer:RequireHttpsMetadata": ""
      "AuthServer:SwaggerClientId": ""
      "AuthServer:SwaggerClientSecret": ""
      "RabbitMq:Host": ""
      "RabbitMq:UserName": ""
      "RabbitMq:Password": ""
      "RabbitMq:VirtualHost": ""
      "StringEncryption:DefaultPassPhrase": ""
      "Stripe:ApiKey": ""
    ports:
      - "21024:80"
    volumes:
      - ./tmp-build/BNB/BnbCore-Host/logs:/app/Logs
      - ./tmp-build/BNB/BnbCore-Host/.aspnet/https:/root/.aspnet/https:ro
      - ./tmp-build/BNB/BnbCore-Host/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    links:
      - rabbitmq:rabbitmq
    depends_on:
      - rabbitmq

  bnb_idv_api:
    container_name: bnb_idv_api
    build:
      context: .
      dockerfile: IDV.Dockerfile
    environment:
      "ASPNETCORE_ENVIRONMENT": "Production"
      "ConnectionStrings:Default": ""
      "App:SelfUrl": ""
      "App:ClientUrl": ""
      "App:RedirectAllowedUrls": ""
      "App:CorsOrigins": ""
      "AuthServer:Authority": ""
      "AuthServer:RequireHttpsMetadata": ""
      "AuthServer:SwaggerClientId": ""
      "AuthServer:SwaggerClientSecret": ""
      "RabbitMq:Host": ""
      "RabbitMq:UserName": ""
      "RabbitMq:Password": ""
      "RabbitMq:VirtualHost": ""
      "StringEncryption:DefaultPassPhrase": ""
      "Stripe:ApiKey": ""
    ports:
      - "21025:80"
    volumes:
      - ./tmp-build/BNB/BnbIdv-Host/logs:/app/Logs
      - ./tmp-build/BNB/BnbIdv-Host/.aspnet/https:/root/.aspnet/https:ro
      - ./tmp-build/BNB/BnbIdv-Host/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro  
    links:
      - rabbitmq:rabbitmq  
    depends_on:
      - rabbitmq  

  bnb_notification_hub_engine:
    container_name: bnb_notification_hub_engine
    build:
      context: .
      dockerfile: Notification.Dockerfile
    environment:
      "ASPNETCORE_ENVIRONMENT": "Production"
      "RabbitMq:Host": ""
      "RabbitMq:UserName": ""
      "RabbitMq:Password": ""
      "RabbitMq:VirtualHost": ""
      "Settings:Host": ""
      "Settings:Port": ""
      "Settings:UserName": ""
      "Settings:Password": ""
      "Settings:SenderName": ""
      "Settings:SenderEmail": ""
      "Settings:Server": ""

    volumes:
      - ./tmp-build/BNB/BnbNotify-Host/logs:/app/Logs
      - ./tmp-build/BNB/BnbNotify-Host/.aspnet/https:/root/.aspnet/https:ro
      - ./tmp-build/BNB/BnbNotify-Host/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro   
    links:
      - rabbitmq:rabbitmq  
    depends_on:
      - rabbitmq  
  proxyapp:
    image: nginx:alpine
    container_name: proxyapp
    environment:
      "FILE_MANAGER_PATH": "/app/App_Data/FileManager"
      
    volumes:
      - ../proxy/conf.d:/etc/nginx/conf.d
    depends_on:
      - bnb_boat_api
      - bnb_booking_api
      - bnb_payment_api
      - bnb_core_api
      - bnb_idv_api
      - bnb_client_portal
    links:
      - bnb_client_portal:bnb_client_portal
      - bnb_boat_api:bnb_boat_api
      - bnb_booking_api:bnb_booking_api
      - bnb_payment_api:bnb_payment_api
      - bnb_core_api:bnb_core_api
      - bnb_idv_api:bnb_idv_api
    ports:
      - "80:80"  