window._env = {
    BOAT_API_URL:'https://localhost:44387',
    BOOKING_API_URL: 'https://localhost:44337',
    CORE_API_URL: 'https://localhost:44347',
    IDENTITY_API_URL: 'https://localhost:44311',
    PAYMENTS_API_URL: 'https://localhost:44366',
    CHAT_API_URL:'https://localhost:44363',
    S3BUCKET_URL:'https://bnbyachts.s3.amazonaws.com',
    CAPTAIN_APP_URL:'http://localhost:4201/',
    MANAGEMENT_APP_URL:'http://localhost:4202/',
    CLEANING_APP_URL:'http://localhost:4203/',
    CLIENT_APP_URL:'http://localhost:4200/',
    stripeKey: "pk_test_51JjjR4IQmeuKTcwEUxVurdeswUrX0kjd0thsgPIYZpOiuPm7wf2XdKjWBjU2FtsT8PGjxmj7lCXU7QPA35qXuRPY00YGIKhP5f",
    identity_authority: "https://localhost:44311",
    identity_redirectUrl: "http://localhost:4202",
    identity_postLogoutRedirectUri: "http://localhost:4202",
    identity_clientId: "BnBYachts_Management",
    identity_scope: "openid Core Booking Boat Payments HostGateway Chat",
    identity_responseType: 'code',
    enableDebug : false
};